# Set the general logging level within the application
logging:
  level:
    io.pivotal.refarch: DEBUG
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: INFO

#spring.datasource.type: com.zaxxer.hikari.HikariDataSource
#spring.datasource.hikari.maximumPoolSize: 4
#
#spring.jpa.generate-ddl: true
#spring.jpa.hibernate.ddl-auto: create-drop
#spring.jpa.show-sql: true
#spring.jpa.hibernate.use-new-id-generator-mappings: true
#spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

your:
  host:
    is: "Allard Buijze"

management:
  endpoint.health.show-details: always
  info.git.mode: full
